import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import { getSessionUser } from "@/lib/auth/server";
import LineWaves from "@/components/animation-ui/LineWaves"; 
import { Navbar } from "@/components/layout/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {

  // Ambil session user buat kebutuhan global
  const user = await getSessionUser();

  return (
    <html
      lang="id"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col relative">
        <LineWaves
          speed={0.3}
          innerLineCount={32}
          outerLineCount={36}
          warpIntensity={1}
          rotation={-45}
          edgeFadeWidth={0.05}
          colorCycleSpeed={1}
          brightness={0.2}
          color1="#9320ff"
          color2="#A855F7"
          color3="#7C3AED"
          enableMouseInteraction
          mouseInfluence={2}
        />

      {/* Bungkus app sama provider user dan navbar */}
        <UserProvider initialUser={user as any}>
          <Navbar />
          <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col px-4 py-8 mt-16">
            {children}
          </main>
        </UserProvider>  
      </body>
    </html>
  );
}
